import pygame, os

# EXTERNAL / API
GH_API = "https://raw.githubusercontent.com/lucmcmullan/pyatc/refs/heads/main/version.txt"



# GLOBAL SIM SETTINGS
WIDTH, HEIGHT = 1500, 600
FPS = 30
SIM_SPEED = 5.0
DEFAULT_FONT = "Consolas"
CURSOR_BLINK_SPEED = 2.0

INITIAL_PLANE_COUNT = 5
ERROR_LOG_FILE = "error_log.txt"

# FEATURE CONTROL
AI_HELPER = False
AI_TRAFFIC = False
RESPONSE_VOICE = False
TRAFFIC_SPAWNING = True

HELPER_LOOKAHEAD_SECONDS = [60, 120, 300]
HELPER_CONFLICT_THRESHOLD = 0.7
HELPER_UPDATE_INTERVAL = 2.0
ML_MODEL_PATH = "models/conflict_model.joblib"

AI_DECISION_PERIOD = 3.0
AI_MIN_ALT = 3000
AI_MAX_ALT = 8000
AI_DECONFLICT_TURN = 25
AI_APPROACH_ARM_DIST_NM = 12.0
AI_ALIGN_ALLOWED_DIFF_DEG = 45
AI_LANDING_SPEED = 160

RUNWAY_SPAWN_PROBABILITY = 0.25
RUNWAY_SPAWN_ALT_FT = 0
RUNWAY_TAKEOFF_DELAY_S = (2.0, 6.0)
SPAWN_INTERVAL_S = 30.0
TRAFFIC_MAX = 30
SPAWN_MARGIN_BASE = 50
SPAWN_HEADING_NORTH = (140, 220)
SPAWN_HEADING_SOUTH_1 = (320, 360)
SPAWN_HEADING_SOUTH_2 = (0, 40)
SPAWN_HEADING_EAST = (220, 320)
SPAWN_HEADING_WEST = (40, 140)
SPAWN_SPEEDS = [180, 220, 250]
SPAWN_ALTS = [2000, 4000, 6000]
DEFAULT_DEST_ALT = 4000

# RADIO / COMMUNICATION
ACK_DELAY_RANGE = (0.5, 1.5)
COMMAND_DELAY_RANGE = (0.5, 2.5)

# AIRSPACE & SEPARATION
SAFE_LAT_NM = 3.0
SAFE_VERT_FT = 1000
LANDING_HEADING_OFFSET_DEG = 60
LANDING_HEIGHT_OFFSET_FT = 3000
NM_PER_PX = 0.08

# RADAR DISPLAY
RADAR_CENTER = (WIDTH // 2, HEIGHT // 2)
SIDEBAR_WIDTH = 260
SIDEBAR_OFFSET = 10
RADAR_WIDTH = WIDTH - SIDEBAR_WIDTH

RADAR_RING_SPACING = 100
RADAR_RING_MAX_RADIUS = 1300
RADAR_FIX_RING_SPACING_NM = (10, 30, 10)
RADAR_HEADING_INTERVAL_DEG = 30
RADAR_LINE_RANGE_NM = 20

# RUNWAYS & AIRPORTS
RUNWAY_BASE_WIDTH = 6
RUNWAY_ACTIVE_WIDTH = 2
RUNWAY_LABEL_OFFSET_X = 10
RUNWAY_LABEL_OFFSET_Y = -5
RUNWAY_NAME_OFFSET_X = 10
RUNWAY_NAME_OFFSET_Y = 10
RUNWAY_DEFAULT_LENGTH_NM = 2.0
RUNWAY_SUFFIX_LR = ["L", "R"]
RUNWAY_SUFFIX_MULTI = ["A", "B", "C", "D", "E", "F"]
RUNWAY_DEFAULT_STATUS = "AVAILABLE"
RUNWAY_OCCUPIED_STATUS = "OCCUPIED"
RUNWAY_CLOSED_STATUS = "CLOSED"

AIRPORT_DEFAULT_ICAO = "EGXX"
AIRPORT_DEFAULT_NAME = "Airport1"

RUNWAYS = [
    {"x": 0.5, "y": 0.6,  "bearing": 270, "length_nm": 2.5},
    {"x": 0.7, "y": 0.65, "bearing": 270, "length_nm": 2.5},
]

FIXES = {
    "DPA":   {"x": 1200, "y": 250},
    "EON":   {"x": 800,  "y": 700},
    "FONTI": {"x": 300,  "y": 150},
    "OBK":   {"x": 300,  "y": 600},
}

# AIRCRAFT PERFORMANCE
EXPEDITE_MULTIPLIER = 2
DEFAULT_CLIMB_RATE_FPM = 1500
EXPEDITE_CLIMB_RATE_FPM = DEFAULT_CLIMB_RATE_FPM * EXPEDITE_MULTIPLIER
ALTITUDE_INTERPOLATION_MIN_DURATION = 1.0
ALTITUDE_SMOOTHING_FACTOR = 0.6
ALTITUDE_STABILISE_DECAY = 0.8
ALTITUDE_STABILISE_FREQ = 4
ALTITUDE_STABILISE_AMPLITUDE = 20
ALTITUDE_STABILISE_END_THRESHOLD = 0.05

TURN_RATE_DEG_PER_SEC = 3.0
SPEED_CHANGE_RATE_KTS_PER_SEC = 50
LANDING_DECEL_RATE_KTS_PER_SEC = 80

TAKEOFF_RELEASE_ALT_FT = 100
TAKEOFF_RELEASE_RATIO = 0.5
LANDING_TOUCHDOWN_ALT_FT = 5
LANDING_ROLLOUT_MIN_SPEED = 30
LANDING_ROLLOUT_MAX_TIME = 8

# UI / COLOURS
COLOUR_BG = (0, 0, 20)
COLOUR_CONSOLE_BG = (20, 20, 20)
COLOUR_CONSOLE_TEXT = (255, 255, 255)

COLOUR_ERROR_BG = (20, 0, 0, 200)
COLOUR_ERROR_HEADER = (255, 255, 0)
COLOUR_ERROR_TEXT = (255, 100, 100)

COLOUR_RUNWAY_BASE = (180, 180, 180)
COLOUR_RUNWAY_AVAILABLE = (255, 255, 255)
COLOUR_RUNWAY_OCCUPIED = (255, 100, 100)
COLOUR_RUNWAY_CLOSED = (100, 100, 100)
COLOUR_RUNWAY_LABEL = (255, 255, 0)

COLOUR_RADAR_BG = (0, 0, 20)
COLOUR_RADAR_GRID = (0, 60, 0)
COLOUR_FIX_RING = (50, 50, 100)
COLOUR_FIX_TEXT = (100, 120, 180)
COLOUR_FIX_CENTER_OUTER = (100, 100, 255)
COLOUR_FIX_CENTER_INNER = (180, 180, 255)
COLOUR_FIX_LABEL = (180, 180, 255)
COLOUR_CONFLICT = (255, 80, 80)

COLOUR_SIDEBAR_BG = (10, 10, 10)
COLOUR_SIDEBAR_BORDER = (60, 60, 60)
COLOUR_EXPAND_ICON_BG = (80, 80, 80)
COLOUR_EXPAND_ICON_X = (255, 255, 0)

COLOUR_FPL_BG = (10, 10, 10)
COLOUR_FPL_BORDER = (100, 100, 100)
COLOUR_FPL_TITLE = (255, 255, 0)
COLOUR_FPL_TEXT = (255, 255, 255)

COLOUR_STATE_AIRBORNE = (20, 80, 20)
COLOUR_STATE_APPROACH = (120, 30, 30)
COLOUR_STATE_TAKEOFF = (120, 120, 30)
COLOUR_STATE_LANDED = (40, 40, 40)
COLOUR_STATE_UNKNOWN = (30, 30, 30)
COLOUR_LEGEND_TEXT = (200, 200, 200)

COLOUR_PLANE_DEFAULT = (0, 255, 0)
COLOUR_PLANE_ACTIVE = (255, 255, 0)
COLOUR_TAG_TEXT = (255, 255, 255)

COLOUR_PERF_BG = (10, 10, 10, 210)
COLOUR_PERF_TEXT = (255, 255, 180)
COLOUR_PERF_BORDER = (255, 255, 0)

COLOUR_MSG_CTRL = (150, 150, 255)
COLOUR_MSG_TEXT = (255, 255, 255)
COLOUR_MSG_PLACEHOLDER = (120, 120, 120)
COLOUR_MSG_SCROLLBAR = (80, 80, 80)
COLOUR_MSG_TITLE = (255, 255, 0)
COLOUR_MSG_HINT = (180, 180, 180)

# --- Modal and Button Colours ---
MODAL_WIDTH = 460
MODAL_HEIGHT = 200
COLOUR_MODAL_BG = (16, 16, 24, 235)
COLOUR_MODAL_CARD = (30, 30, 40, 255)
COLOUR_MODAL_TEXT = (255, 255, 255)
COLOUR_MODAL_SUB = (200, 200, 200)
COLOUR_BTN_BG = (70, 130, 180)
COLOUR_BTN_TEXT = (255, 255, 255)
COLOUR_BTN_BG_HOVER = (90, 150, 200)

# WINDOW LABELS
WINDOW_MAIN = "PyATC"
WINDOW_HELP = "Help"
WINDOW_PERFORMANCE = "Performance"
WINDOW_FLIGHT_PROGRESS = "Flight Progress"
WINDOW_ERROR = "Error"
WINDOW_AC_PROFILE = "Aircraft Profile"

#  FLIGHT PLAN / TAG LAYOUT
FPL_MARGIN_X = 10
FPL_MARGIN_Y = 50
FPL_WIDTH_OFFSET = 20
FPL_HEIGHT_MARGIN = 100
FPL_ROW_HEIGHT = 24
FPL_LEGEND_HEIGHT = 90

PLANE_ICON_SIZE = 8
PLANE_HEADING_LINE_LENGTH = 25
PLANE_TAG_OFFSET_X = 10
PLANE_TAG_OFFSET_Y_CALLSIGN = -20
PLANE_TAG_OFFSET_Y_INFO = -5

# COMMANDS / MESSAGES
CMD_TURN_TOKENS = ("L", "R", "X", "EX")
CMD_TAKEOFF_PARAMS_REQUIRED = 3
ALTITUDE_STEP_FT = 1000

MSG_NO_COMMAND = "NO COMMAND"
MSG_NO_INPUT = "No input provided."
MSG_INVALID_TAKEOFF = "unable, invalid takeoff parameters"
MSG_RUNWAY_NOT_FOUND = "unable, runway {rwy} not found"
MSG_RUNWAY_OCCUPIED = "unable, {rwy} occupied"
MSG_NOT_ALIGNED = "unable, not aligned for {rwy}"
MSG_TOO_HIGH = "unable, too high for approach"
MSG_LAND_CLEARANCE = "cleared to land runway {rwy}"
MSG_TAKEOFF_CLEARANCE = "cleared for takeoff runway {rwy}, climb to {alt} feet, maintain {spd} knots"
MSG_HOLD_POS = "hold position"
MSG_HOLD_FIX = "hold at {fix}"
MSG_TAKEOFF_MISSING_PARAMS = "takeoff clearance missing parameters"
MSG_LANDING_MISSING_RUNWAY = "landing clearance missing runway"
MSG_REQUEST_TAKEOFF = "{cs} requesting takeoff runway {rwy}"
MSG_TAKEOFF_ACK = "roger {cs}, hold position, standby for takeoff clearance"

# AIRLINES
AIRLINES = {
    "British Airways": {"IATA": "BA", "ICAO": "BAW", "Callsign": "Speedbird"},
    "EasyJet": {"IATA": "U2", "ICAO": "EZY", "Callsign": "Easy"},
    "Loganair": {"IATA": "LM", "ICAO": "LOG", "Callsign": "Logan"},
    "Ryanair": {"IATA": "RK", "ICAO": "RUK", "Callsign": "Bluemax"},
    "Wizz Air": {"IATA": "W9", "ICAO": "WUK", "Callsign": "Wizz Go"},
}

# FUNCTION KEYS

FUNCTION_KEYS = {
    "help": pygame.K_F1,
    "performance": pygame.K_F2,
    "flight_progress": pygame.K_F3,
    "ai_mode": pygame.K_F4,
    "voice_response": pygame.K_F5,
    "errors": pygame.K_F12,
}

# HELP TEXT

HELP_TEXT = """\
BASIC CONTROLS
    F1 - Open this Help window
    F2 - Open Performance window
    F3 - Open Flight Progress Log
    F4 - Toggle AI simulated planes
    F5 - Toggle voice responses
    ESC - Close detached windows

COMMAND INPUT
    Enter commands in the bottom console.
    Commands can be chained using '|'.
    Example: SPEEDBIRD123 HDG 180 | ALT 5000 | SPD 220

COMMON COMMANDS
    HELP - Show this help window
    AI - Return selected aircraft to AI control
    SPD <value> - Set aircraft speed (in knots)
    HDG <value> - Set aircraft heading (in degrees)
    ALT <value> - Set altitude (in feet)
    LAND <runway> - Instruct aircraft to land on a runway
    TAKEOFF <runway> <speed> <altitude> - Begin takeoff if aircraft is on a runway

NOTES
    Click on aircraft to auto-fill its callsign.
    Clicking off any aircraft clears selection.
    Use '|' to sequence multiple instructions.
    Aircraft acknowledge commands realistically.
    AI aircraft spawn automatically every 30 s when enabled.

PyATC © 2025 Luc McMullan
"""

PLANE_TYPES = ["A320", "B747", "E190", "C172", "B77W", "A359", "B738"]